### PR TITLE
`Model.save(object)` should resolve with single object

### LINKED ISSUE #275: `Model.save(object)` resolves with an array
This might be a regression. I seem to recall seeing a similar issue in the past, but I can't find it.

### PR DESCRIPTION
**Pull request by marshall007**
Fixes #275. After looking at the tests it appears that we were expecting what I would consider the "incorrect" behavior. If the current behavior is intentional feel free to close this and the related issue, just note that it's not [currently documented](http://thinky.io/documentation/api/model/#save) one way or the other right now.

### CODE REVIEW

File: lib/model.js [hunk 1]
```diff
@@ -1064,6 +1065,11 @@ Model.prototype.save = function(docs, options) {
       });
     }
   })
+
+  if (!isArray) {
+    return p.get(0);
```
Comment (neumino) [inline lib/model.js]: I just wanted to say that this is pretty neat. I like it.

**Comment by neumino** [comment]
The main reason behind `Model.save` was to allow batch inserts. I don't remember anyone explicitly asking for an array instead of an object in case of a single insert.

Your pull request seems to be the appropriate behavior IMO. Since it's a non-backward compatible change, I'm leaving people a few days before merging. If no objections, I'll merge it as it is since the code is good :)

Thanks again @marshall007 :)

**Comment by marshall007** [comment]
I like using `Model.save` because `document.save` doesn't currently support the `conflict` optarg. By setting `conflict:update` you can avoid the extra step of having to use `document.setSaved()`.

File: lib/model.js (hunk 1 above)
Comment (marshall007) [inline lib/model.js]: Yea, bluebird is awesome :)

**Comment by neumino** [comment]
Merging since no one has complained :)
Thanks @marshall007
